Repository AY2021S2-CS2103T-W10-1/tp, pull requests merged in 2021-03, with the labels that each got.

#29 Update personal portfolio page
  docs/team/joelho.md
Labels: priority.Low, severity.VeryLow, type.Task

#28 Remove redundant proposed features
  docs/DeveloperGuide.md
Labels: priority.High, severity.VeryLow, type.Task

#24 Update landing page
  docs/index.md
Labels: priority.High, severity.VeryLow, type.Task

#32 Update userguide
  docs/UserGuide.md
Labels: priority.High, severity.VeryLow, type.Task

#40 Add driver class and prerequisite Human abstract class as parent
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/human/Human.java
  src/main/java/seedu/address/model/human/Name.java
  src/main/java/seedu/address/model/human/Phone.java
  src/main/java/seedu/address/model/human/driver/Driver.java
  src/main/java/seedu/address/model/human/person/Address.java
  src/main/java/seedu/address/model/human/person/Email.java
  src/main/java/seedu/address/model/human/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/human/person/Person.java
  src/main/java/seedu/address/model/human/person/UniquePersonList.java
  src/main/java/seedu/address/model/human/person/exceptions/DuplicatePersonException.java
  src/main/java/seedu/address/model/human/person/exceptions/PersonNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/human/person/AddressTest.java
  src/test/java/seedu/address/model/human/person/EmailTest.java
  src/test/java/seedu/address/model/human/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/human/person/NameTest.java
  src/test/java/seedu/address/model/human/person/PersonTest.java
  src/test/java/seedu/address/model/human/person/PhoneTest.java
  src/test/java/seedu/address/model/human/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#53 Add fields to person
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/human/Human.java
  src/main/java/seedu/address/model/human/driver/Driver.java
  src/main/java/seedu/address/model/human/person/Address.java
  src/main/java/seedu/address/model/human/person/Email.java
  src/main/java/seedu/address/model/human/person/Person.java
  src/main/java/seedu/address/model/human/person/TripDay.java
  src/main/java/seedu/address/model/human/person/TripTime.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/human/NameTest.java
  src/test/java/seedu/address/model/human/PhoneTest.java
  src/test/java/seedu/address/model/human/driver/DriverTest.java
  src/test/java/seedu/address/model/human/person/EmailTest.java
  src/test/java/seedu/address/model/human/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/human/person/PersonTest.java
  src/test/java/seedu/address/model/human/person/TripDayTest.java
  src/test/java/seedu/address/model/human/person/TripTimeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/DriverBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalDrivers.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#57 Add drive command
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/DriveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DriveCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/human/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DriveCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DriveCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/human/person/PersonTest.java
  src/test/java/seedu/address/testutil/CommuterBuilder.java
  src/test/java/seedu/address/testutil/DriverBuilder.java
  src/test/java/seedu/address/testutil/DriverUtil.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Story

#67 Update Add and Edit command message responses
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: priority.High, type.Bug

#66 Update Add and Edit command user guide
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: priority.High, type.Bug

#68 Update user guide
  docs/UserGuide.md
Labels: priority.High, type.Bug

#62 Update User Guide Drive command
  docs/UserGuide.md
Labels: priority.High, severity.High

#71 Update Personal Portfolio info
  docs/team/joelho.md
Labels: severity.VeryLow

#73 Update UI to match mockup design
  docs/images/github-icon.png
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/human/person/IsAssignedDriverPredicate.java
  src/main/java/seedu/address/ui/FreePersonListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TakenPersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Story

#96 Rename drive command to pool
  src/main/java/seedu/address/logic/commands/PoolCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/PoolCommandParser.java
  src/test/java/seedu/address/logic/commands/PoolCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/PoolCommandParserTest.java
  src/test/java/seedu/address/testutil/DriverUtil.java
Labels: priority.Medium

#91 Add price to person
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/PoolCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/passenger/Passenger.java
  src/main/java/seedu/address/model/person/passenger/Price.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPassenger.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/passenger/PassengerTest.java
  src/test/java/seedu/address/model/person/passenger/PriceTest.java
  src/test/java/seedu/address/testutil/PassengerBuilder.java
  src/test/java/seedu/address/testutil/PassengerUtil.java
  src/test/java/seedu/address/testutil/TypicalPassengers.java
Labels: priority.High, severity.High, type.Story

#101 Add unpool command
  src/main/java/seedu/address/logic/commands/UnpoolCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UnpoolCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/passenger/IsSpecifiedDriverPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/UnpoolCommandTest.java
  src/test/java/seedu/address/logic/parser/UnpoolCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPassengers.java
Labels: priority.High

#100 Change datatypes of TripDay, TripTime, and Price
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/passenger/Passenger.java
  src/main/java/seedu/address/model/person/passenger/Price.java
  src/main/java/seedu/address/model/person/passenger/TripDay.java
  src/main/java/seedu/address/model/person/passenger/TripTime.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPassenger.java
  src/main/java/seedu/address/ui/PassengerCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePassengersAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPassengersAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/passenger/PriceTest.java
  src/test/java/seedu/address/model/person/passenger/TripDayTest.java
  src/test/java/seedu/address/model/person/passenger/TripTimeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPassengerTest.java
  src/test/java/seedu/address/testutil/EditPassengerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PassengerBuilder.java
  src/test/java/seedu/address/testutil/PassengerUtil.java
  src/test/java/seedu/address/testutil/TypicalPassengers.java
Labels: priority.Medium, severity.Low

#105 Amend user guide
  docs/UserGuide.md
Labels: priority.Medium, type.Enhancement

#110 Modify find command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/passenger/PriceContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High, type.Enhancement

#111 Add Trip object class
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/PoolCommand.java
  src/main/java/seedu/address/logic/commands/UnpoolCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/passenger/Passenger.java
  src/main/java/seedu/address/model/pool/Pool.java
  src/main/java/seedu/address/model/pool/TripDay.java
  src/main/java/seedu/address/model/pool/TripTime.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPassenger.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/passenger/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/pool/TripDayTest.java
  src/test/java/seedu/address/model/pool/TripTimeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPassengerTest.java
  src/test/java/seedu/address/testutil/EditPassengerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PassengerBuilder.java
Labels: priority.High, type.Story

#113 Implement pool list
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/PoolCommand.java
  src/main/java/seedu/address/logic/commands/UnpoolCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/passenger/IsAssignedDriverPredicate.java
  src/main/java/seedu/address/model/person/passenger/IsSpecifiedDriverPredicate.java
  src/main/java/seedu/address/model/person/passenger/Passenger.java
  src/main/java/seedu/address/model/pool/Pool.java
  src/main/java/seedu/address/model/pool/UniquePoolList.java
  src/main/java/seedu/address/model/pool/exceptions/DuplicatePoolException.java
  src/main/java/seedu/address/model/pool/exceptions/PoolNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPassenger.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PassengerCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/PoolCommandTest.java
  src/test/java/seedu/address/logic/commands/UnpoolCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/passenger/PassengerTest.java
  src/test/java/seedu/address/model/pool/PoolTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPassengerTest.java
  src/test/java/seedu/address/testutil/DriverBuilder.java
  src/test/java/seedu/address/testutil/PassengerBuilder.java
  src/test/java/seedu/address/testutil/PassengerSetBuilder.java
  src/test/java/seedu/address/testutil/PoolBuilder.java
  src/test/java/seedu/address/testutil/TypicalPassengers.java
  src/test/java/seedu/address/testutil/TypicalPools.java
Labels: priority.High

#112 Remove AB-3 References in DG
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/_sass/minima/_base.scss
Labels: priority.High

#128 Update user guide with unpool command
  docs/UserGuide.md
Labels: priority.High

#130 Fix card empty space and add header for panels
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PassengerListCard.fxml
  src/main/resources/view/PoolListCard.fxml
Labels: priority.High, severity.Low

#141 Change to StringJoiner from StringBuilder
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: priority.Medium
