Repository AY2021S2-CS2103T-W10-1/tp, pull requests merged in 2021-04, with the labels that each got.

#146 Improve code coverage
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/PoolCommand.java
  src/main/java/seedu/address/logic/commands/UnpoolCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PoolCommandParser.java
  src/main/java/seedu/address/model/TripDay.java
  src/main/java/seedu/address/model/TripDayContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/TripTime.java
  src/main/java/seedu/address/model/TripTimeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/passenger/Passenger.java
  src/main/java/seedu/address/model/pool/DriverNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/pool/Pool.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPassenger.java
  src/main/java/seedu/address/storage/JsonAdaptedPool.java
  src/main/java/seedu/address/storage/StorageUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/PoolCommandTest.java
  src/test/java/seedu/address/logic/commands/UnpoolCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PoolCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/driver/DriverTest.java
  src/test/java/seedu/address/model/pool/PoolTest.java
  src/test/java/seedu/address/model/pool/TripDayTest.java
  src/test/java/seedu/address/model/pool/TripTimeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPassengerTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditPassengerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PassengerBuilder.java
  src/test/java/seedu/address/testutil/PoolBuilder.java
  src/test/java/seedu/address/testutil/PoolUtil.java
  src/test/java/seedu/address/testutil/TypicalDrivers.java
  src/test/java/seedu/address/testutil/TypicalPassengers.java
  src/test/java/seedu/address/testutil/TypicalPools.java
  src/test/java/seedu/address/ui/DriverCardTest.java
Labels: priority.Medium, severity.Low, type.Task

#214 Update UG and command message for Find
  docs/UserGuide.md
  docs/images/findAddress.png
  docs/images/findCommandExampleDay.png
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: severity.VeryLow, type.Bug

#217 Fix errors and inconsistencies in UG found during PE-D
  docs/UserGuide.md
Labels: priority.High, type.Bug

#226 Modify UG formatting
  docs/UserGuide.md
Labels: priority.Medium, severity.Medium, type.Bug

#218 More test coverage
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/driver/Driver.java
  src/main/java/seedu/address/model/person/passenger/PriceIsGreaterThanAmountPredicate.java
  src/main/java/seedu/address/model/pool/Pool.java
  src/main/java/seedu/address/storage/JsonAdaptedDriver.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/driver/DriverTest.java
  src/test/java/seedu/address/model/person/passenger/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/passenger/PriceIsGreaterThanAmountPredicateTest.java
  src/test/java/seedu/address/model/pool/PoolTest.java
  src/test/java/seedu/address/model/pool/PooledPassengerContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/pool/UniquePoolListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDriverTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPassengerTest.java
Labels: priority.Medium, type.Enhancement

#227 Fix missing listPool
  src/main/java/seedu/address/logic/commands/ListPoolCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/FindPoolCommandTest.java
  src/test/java/seedu/address/logic/commands/ListPoolCommandTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: priority.High, severity.High, type.Bug

#254 Fix price not showing on Passenger's Card
  src/main/java/seedu/address/ui/DriverCard.java
  src/main/java/seedu/address/ui/PassengerCard.java
  src/main/resources/images/price.png
  src/main/resources/view/PassengerListCard.fxml
  src/main/resources/view/PoolListCard.fxml
  src/test/java/seedu/address/ui/DriverCardTest.java
Labels: priority.High, severity.High, type.Bug

#262 Make price field hide also when equal zero
  src/main/java/seedu/address/ui/PassengerCard.java
Labels: priority.High, type.Bug

#266 More tests for FindPoolCommandParser, Refactor magic literals
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindPoolCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPoolCommandTest.java
  src/test/java/seedu/address/logic/parser/FindPoolCommandParserTest.java
Labels: type.Enhancement

#246 Update DG with better consistencies for wording and include FindPool implementation
  docs/DeveloperGuide.md
  docs/diagrams/ListPoolSequenceDiagram.puml
  docs/images/ListPoolSequenceDiagram.png
Labels: priority.High, type.Task
